'use client'

import { useEffect, useState } from 'react'

type Client = { id:string; name:string; email:string|null; phone:string|null; address:string|null; active:boolean; created_at:string }

export default function ClientsPage(){
 const [clients,setClients]=useState<Client[]>([]); const [loading,setLoading]=useState(true); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const [form,setForm]=useState({name:'',email:'',phone:'',address:''})
 useEffect(()=>{fetch('/api/customers').then(r=>r.json()).then(d=>{setClients(d.customers||[]);setError(d.error||'')}).catch(()=>setError('Unable to load clients.')).finally(()=>setLoading(false))},[])
 async function createClient(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');const r=await fetch('/api/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok){setError(d.error||'Unable to create client.')}else{setClients(x=>[d.customer,...x]);setForm({name:'',email:'',phone:'',address:''});setOpen(false)}setSaving(false)}
 return <div className="erp-shell"><style>{`.client-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.client-card{border:1px solid #e4e7e3;padding:18px;background:#fff}.client-avatar{width:34px;height:34px;border:1px solid #dfe3de;display:grid;place-items:center;font-size:11px;font-weight:700;margin-bottom:13px}.client-card h3{margin:0 0 5px;font-size:13px}.client-card p{margin:3px 0;color:#7d857e;font-size:9px;line-height:1.5}.client-status{display:inline-block;margin-top:12px;font-size:7px;padding:4px 6px;background:#f0f4ef;color:#657067}.modal-back{position:fixed;inset:0;background:#0005;display:grid;place-items:center;padding:18px;z-index:20}.modal{width:min(520px,100%);background:#fff;padding:24px;border:1px solid #ddd}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{display:grid;gap:6px}.field.full{grid-column:1/-1}.field label{font-size:8px;text-transform:uppercase;letter-spacing:.08em;color:#737b75}.field input,.field textarea{font:inherit;border:1px solid #dfe3de;padding:11px;background:#fff}.field textarea{min-height:80px;resize:vertical}.modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.empty{padding:35px;text-align:center;color:#7c847e;font-size:10px}@media(max-width:900px){.client-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.client-grid,.form-grid{grid-template-columns:1fr}.field.full{grid-column:auto}}`}</style>
 <aside className="erp-sidebar"><div className="erp-brand"><span className="brand-mark">M</span><div><strong>MILLIMETRE</strong><small>Furniture ERP</small></div></div><div className="workspace">CLIENT WORKSPACE <span>⌄</span></div><nav><a href="/executive"><span className="nav-dot"/>Dashboard</a><a href="/projects"><span className="nav-dot"/>Projects</a><a className="active" href="/clients"><span className="nav-dot"/>Clients</a><a href="/measurements"><span className="nav-dot"/>Measurements</a><a href="/furniture"><span className="nav-dot"/>Furniture</a><a href="/master"><span className="nav-dot"/>Master Pages</a><a href="/templates"><span className="nav-dot"/>Templates</a><a href="/team"><span className="nav-dot"/>Team</a><a href="/settings"><span className="nav-dot"/>Settings</a></nav><div className="sidebar-bottom"><a href="/account">◉ Subscription</a><a href="/sign-out">↪ Sign out</a></div></aside>
 <main className="erp-main"><header className="erp-header"><div><div className="eyebrow">FOUNDATION / CLIENTS</div><h1>Every project starts with a client.</h1><p>Keep customer contacts and delivery information in one record, then link projects, quotations and procurement back to it.</p></div><div className="header-actions"><a className="ghost-btn" href="/projects">View projects</a><button className="primary-btn" onClick={()=>setOpen(true)}>+ New client</button></div></header>
 <section className="metric-grid"><div className="metric-card"><span>Total clients</span><strong>{clients.length}</strong><small>Active customer records</small></div><div className="metric-card"><span>Active</span><strong>{clients.filter(c=>c.active).length}</strong><small>Available for new projects</small></div><div className="metric-card"><span>Project linking</span><strong>Ready</strong><small>Client → Project → Commercials</small></div><div className="metric-card"><span>Contact data</span><strong>Central</strong><small>Email · phone · site address</small></div></section>
 <section className="panel"><div className="panel-head"><div><h2>Client directory</h2><p>Searchable customer foundation for the complete project lifecycle.</p></div><span className="master-badge">CLIENT MASTER</span></div>{error&&<p role="alert" style={{padding:'12px 18px',color:'#a34'}}>{error}</p>}{loading?<div className="empty">Loading clients…</div>:clients.length?<div className="client-grid" style={{padding:18}}>{clients.map(c=><article className="client-card" key={c.id}><div className="client-avatar">{c.name.slice(0,2).toUpperCase()}</div><h3>{c.name}</h3><p>{c.email||'No email recorded'}</p><p>{c.phone||'No phone recorded'}</p><p>{c.address||'No site / delivery address recorded'}</p><span className="client-status">{c.active?'ACTIVE':'INACTIVE'}</span></article>)}</div>:<div className="empty">No clients yet. Create the first customer before opening a live project.</div>}</section>
 <section className="content-grid"><section className="panel"><div className="panel-head"><div><h2>Client → project flow</h2><p>A client can anchor the full commercial and execution history.</p></div></div><div className="flow-steps"><div><b>01</b><span>Client</span><small>Contact + delivery details</small></div><i>→</i><div><b>02</b><span>Project</span><small>Site, rooms and furniture</small></div><i>→</i><div><b>03</b><span>Quotation</span><small>Costing + approval</small></div><i>→</i><div><b>04</b><span>Execution</span><small>Purchase → production → handover</small></div></div></section><section className="panel"><div className="panel-head"><div><h2>Onboarding checklist</h2><p>Capture enough information to start the project correctly.</p></div></div><div className="setup-list"><div><b>01</b><span>Client / company name</span><em>REQUIRED</em></div><div><b>02</b><span>Direct phone and email</span><em>CONTACT</em></div><div><b>03</b><span>Site / delivery address</span><em>PROJECT</em></div><div><b>04</b><span>Create linked project</span><em>NEXT</em></div></div></section></section></main>
 {open&&<div className="modal-back"><form className="modal" onSubmit={createClient}><div className="panel-head" style={{padding:0,border:0}}><div><div className="eyebrow">NEW CLIENT</div><h2 style={{margin:'6px 0'}}>Customer onboarding</h2><p>Create the customer record that projects and quotations will reference.</p></div><button type="button" className="ghost-btn" onClick={()=>setOpen(false)}>Close</button></div><div className="form-grid"><div className="field full"><label>Name / Company</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} /></div><div className="field"><label>Email</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="field"><label>Phone</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="field full"><label>Site / Delivery Address</label><textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div></div>{error&&<p role="alert" style={{color:'#a34',fontSize:9}}>{error}</p>}<div className="modal-actions"><button type="button" className="ghost-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Creating…':'Create client'}</button></div></form></div>}
 </div>
}