'use client'

import { useEffect, useState } from 'react'
import { getSupabaseBrowserClient } from '../../lib/supabase-browser'

const periods=[7,30,90,365]

export default function SalesDashboard(){
 const [days,setDays]=useState(30); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 async function load(){setLoading(true);setError('');const s=getSupabaseBrowserClient();const {data,error}=await s.rpc('get_sales_activity_dashboard',{p_days:days});if(error)setError(error.message);else setData(data);setLoading(false)}
 useEffect(()=>{load()},[days])
 const c=data?.activity_counts||{}; const f=data?.funnel||{}; const max=Math.max(...(data?.daily||[]).map((x:any)=>Number(x.activities)),1)
 return <main className="page-shell"><div className="page-header"><div><span className="eyebrow">MILLIMETRE SALES</span><h1>Sales activity dashboard</h1><p>Track engagement, follow-ups, pipeline movement and conversion performance.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{periods.map(p=><button key={p} className={days===p?'primary-btn':'ghost-btn'} onClick={()=>setDays(p)}>{p}d</button>)}</div></div>{error&&<div className="panel" style={{marginBottom:18}}>{error}</div>}{loading?<section className="panel">Loading sales intelligence…</section>:<><section className="metric-grid">{[['Calls',c.calls],['WhatsApp',c.whatsapp],['Emails',c.emails],['Meetings',c.meetings],['Follow-ups',c.followups],['Engaged leads',c.engaged_leads]].map(([label,value])=><div className="metric-card" key={label}><span>{label}</span><strong>{value||0}</strong><small>Last {days} days</small></div>)}</section><section className="content-grid"><div className="panel"><div className="panel-head"><div><h2>Activity trend</h2><p>Sales interactions by day</p></div></div><div style={{display:'grid',gap:8}}>{(data?.daily||[]).map((x:any)=><div key={x.day} style={{display:'grid',gridTemplateColumns:'90px 1fr 42px',gap:10,alignItems:'center'}}><small>{x.day}</small><div style={{height:12,borderRadius:99,background:'var(--line,#e5e7eb)',overflow:'hidden'}}><div style={{height:'100%',width:`${Math.max(3,Number(x.activities)/max*100)}%`,background:'var(--ink,#111)'}}/></div><small>{x.activities}</small></div>)}</div></div><div className="panel"><div className="panel-head"><div><h2>Pipeline funnel</h2><p>Current demo lead distribution</p></div></div><div style={{display:'grid',gap:12}}>{[['New',f.new_leads],['Contacted',f.contacted],['Qualified',f.qualified],['Demo scheduled',f.demos],['Converted',f.converted],['Closed',f.closed]].map(([label,value])=><div key={label} style={{display:'flex',justifyContent:'space-between',padding:'12px 0',borderBottom:'1px solid var(--line,#e5e7eb)'}}><span>{label}</span><strong>{value||0}</strong></div>)}</div></div></section><section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Owner performance</h2><p>Leads, activities and conversions by sales owner</p></div></div><div className="project-list">{(data?.owners||[]).length?(data.owners.map((o:any)=><div key={o.owner} style={{display:'grid',gridTemplateColumns:'1.5fr 1fr 1fr 1fr',gap:12,padding:'14px 0',borderBottom:'1px solid var(--line,#e5e7eb)'}}><b>{o.owner}</b><span>{o.leads} leads</span><span>{o.activities} activities</span><strong>{o.converted} converted</strong></div>)): <small>No owner activity yet.</small>}</div></section></>}</main>
}
