'use client'

import { useEffect, useState } from 'react'
import { getSupabaseBrowserClient } from '../../lib/supabase-browser'

const periods=[7,30,90,365]
const leadFilter=(params:string)=>`/demo-leads?${params}`

export default function SalesDashboard(){
 const [days,setDays]=useState(30); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 async function load(){setLoading(true);setError('');const s=getSupabaseBrowserClient();const {data,error}=await s.rpc('get_sales_activity_dashboard',{p_days:days});if(error)setError(error.message);else setData(data);setLoading(false)}
 useEffect(()=>{load()},[days])
 const c=data?.activity_counts||{}; const f=data?.funnel||{}; const max=Math.max(...(data?.daily||[]).map((x:any)=>Number(x.activities)),1)
 const activityCards=[['Calls',c.calls,'CALL'],['WhatsApp',c.whatsapp,'WHATSAPP'],['Emails',c.emails,'EMAIL'],['Meetings',c.meetings,'MEETING'],['Follow-ups',c.followups,'FOLLOW_UP'],['Engaged leads',c.engaged_leads,'ENGAGED']]
 const funnel=[['New','NEW'],['Contacted','CONTACTED'],['Qualified','QUALIFIED'],['Demo scheduled','DEMO_SCHEDULED'],['Converted','CONVERTED'],['Closed','CLOSED']]
 return <main className="page-shell"><div className="page-header"><div><span className="eyebrow">MILLIMETRE SALES</span><h1>Sales activity dashboard</h1><p>Track engagement, follow-ups, pipeline movement and conversion performance.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{periods.map(p=><button key={p} className={days===p?'primary-btn':'ghost-btn'} onClick={()=>setDays(p)}>{p}d</button>)}<a className="ghost-btn" href="/demo-leads">Open CRM →</a></div></div>{error&&<div className="panel" style={{marginBottom:18}}>{error}</div>}{loading?<section className="panel">Loading sales intelligence…</section>:<><section className="metric-grid">{activityCards.map(([label,value,type])=><a className="metric-card" href={leadFilter(`activity=${type}&days=${days}`)} key={label}><span>{label}</span><strong>{value||0}</strong><small>Last {days} days · View leads →</small></a>)}</section><section className="content-grid"><div className="panel"><div className="panel-head"><div><h2>Activity trend</h2><p>Sales interactions by day</p></div></div><div style={{display:'grid',gap:8}}>{(data?.daily||[]).map((x:any)=><div key={x.day} style={{display:'grid',gridTemplateColumns:'90px 1fr 42px',gap:10,alignItems:'center'}}><small>{x.day}</small><div style={{height:12,borderRadius:99,background:'var(--line,#e5e7eb)',overflow:'hidden'}}><div style={{height:'100%',width:`${Math.max(3,Number(x.activities)/max*100)}%`,background:'var(--ink,#111)'}}/></div><small>{x.activities}</small></div>)}</div></div><div className="panel"><div className="panel-head"><div><h2>Pipeline funnel</h2><p>Current demo lead distribution</p></div></div><div style={{display:'grid',gap:12}}>{funnel.map(([label,key])=><a href={leadFilter(`status=${key}`)} key={label} style={{display:'flex',justifyContent:'space-between',padding:'12px 0',borderBottom:'1px solid var(--line,#e5e7eb)',textDecoration:'none',color:'inherit'}}><span>{label}</span><strong>{f[key.toLowerCase()]||0} →</strong></a>)}</div></div></section><section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Owner performance</h2><p>Leads, activities and conversions by sales owner</p></div></div><div className="project-list">{(data?.owners||[]).length?(data.owners.map((o:any)=><a href={leadFilter(`owner=${o.owner_id}`)} key={o.owner_id||o.owner} style={{display:'grid',gridTemplateColumns:'1.5fr 1fr 1fr 1fr',gap:12,padding:'14px 0',borderBottom:'1px solid var(--line,#e5e7eb)',textDecoration:'none',color:'inherit'}}><b>{o.owner}</b><span>{o.leads} leads</span><span>{o.activities} activities</span><strong>{o.converted} converted →</strong></a>)): <small>No owner activity yet.</small>}</div></section></>}</main>
}
