export const ENGINE_VERSION = 'millimetre-engine-v1.0.0'
export type EdgeBanding={top?:number;bottom?:number;left?:number;right?:number}
export type Panel={id:string;partOf:string;description:string;length:number;width:number;qty:number;banding:EdgeBanding;grain:'horizontal'|'vertical'|'none';innerPasting?:string;outerPasting?:string;remarks?:string}
export type PlacedPanel=Panel&{sheet:number;x:number;y:number;placedLength:number;placedWidth:number;rotated:boolean}
const n=(v:number)=>Math.round(v*100)/100
export function deriveCarcase(W:number,H:number,D:number,T:number,backMargin=10,grooveDepth=0.5):Panel[]{
if([W,H,D,T].some(v=>!Number.isFinite(v)||v<=0))throw new Error('W, H, D and substrate thickness must be greater than zero.')
if(W<=2*T||H<=2*backMargin||D<=backMargin+5)throw new Error('Carcase dimensions are outside safe manufacturing limits.')
return [{id:'L',partOf:'Carcase',description:'Left Side Panel',length:H,width:D,qty:1,banding:{top:.8,bottom:.8},grain:'none'},{id:'R',partOf:'Carcase',description:'Right Side Panel',length:H,width:D,qty:1,banding:{top:.8,bottom:.8},grain:'none'},{id:'T',partOf:'Carcase',description:'Top Panel',length:W-2*T,width:D,qty:1,banding:{top:.8,bottom:.8},grain:'none'},{id:'B',partOf:'Carcase',description:'Bottom Panel',length:W-2*T,width:D,qty:1,banding:{top:.8,bottom:.8},grain:'none'},{id:'BK',partOf:'Carcase',description:'Back Panel',length:H-2*backMargin+2*grooveDepth,width:W-2*backMargin+2*grooveDepth,qty:1,banding:{},grain:'none'},{id:'S1',partOf:'Carcase',description:'Internal Shelf',length:W-2*T-2,width:D-backMargin-5,qty:1,banding:{top:0,bottom:0,left:0,right:2},grain:'none'},{id:'D1',partOf:'Carcase',description:'Front Shutter',length:H-3,width:W/2-2,qty:2,banding:{top:2,bottom:2,left:2,right:2},grain:'none'}].map(p=>({...p,length:n(p.length),width:n(p.width)}))}
export function applyBanding(p:Panel){const e=p.banding||{};const rawLength=n(p.length-(e.top||0)-(e.bottom||0));const rawWidth=n(p.width-(e.left||0)-(e.right||0));if(rawLength<=0||rawWidth<=0)throw new Error('Edge banding exceeds finished panel dimension.');return{rawLength,rawWidth,surfaceSqft:p.length*p.width/92903.04,bandingMeters:((e.top||0)+(e.bottom||0))*p.width/1000+((e.left||0)+(e.right||0))*p.length/1000}}
function orientations(p:Panel){return p.grain==='none'?[{w:p.width,h:p.length,r:false},{w:p.length,h:p.width,r:true}]:[{w:p.width,h:p.length,r:false}]}
export function optimizeGuillotine(panels:Panel[],sheetW=2438.4,sheetH=1219.2,kerf=4,trim=10){const usableW=sheetW-2*trim,usableH=sheetH-2*trim;const placed:PlacedPanel[]=[];const sheets:{free:{x:number;y:number;w:number;h:number}[];usedArea:number}[]=[];const expanded=panels.flatMap(p=>Array.from({length:p.qty},(_,i)=>({...p,id:p.qty>1?p.id+'-'+(i+1):p.id,qty:1}))).sort((a,b)=>b.length*b.width-a.length*a.width);for(const p of expanded){let best:any=null;for(let si=0;si<sheets.length;si++)for(let fi=0;fi<sheets[si].free.length;fi++){const f=sheets[si].free[fi];for(const o of orientations(p))if(o.w<=f.w&&o.h<=f.h){const leftover=f.w*f.h-o.w*o.h,short=Math.min(f.w-o.w,f.h-o.h),score=leftover*.001+short;if(!best||score<best.score)best={si,fi,o,score}}}if(!best){sheets.push({free:[{x:0,y:0,w:usableW,h:usableH}],usedArea:0});best={si:sheets.length-1,fi:0,o:null,score:Infinity};for(const o of orientations(p))if(o.w<=usableW&&o.h<=usableH){best.o=o;break}}if(!best.o)continue;const s=sheets[best.si],f=s.free.splice(best.fi,1)[0],o=best.o;const rightW=f.w-o.w-kerf,topH=f.h-o.h-kerf;if(rightW>0)s.free.push({x:f.x+o.w+kerf,y:f.y,w:rightW,h:f.h});if(topH>0)s.free.push({x:f.x,y:f.y+o.h+kerf,w:o.w,h:topH});s.usedArea+=o.w*o.h;placed.push({...p,sheet:best.si+1,x:f.x,y:f.y,placedLength:o.h,placedWidth:o.w,rotated:o.r})}const stock=sheets.length*usableW*usableH,panelArea=placed.reduce((a,p)=>a+p.length*p.width,0);return{sheets:sheets.length,placed,failed:expanded.length-placed.length,sawStrokes:placed.length+sheets.reduce((a,s)=>a+s.free.length,0),usableSheetArea:usableW*usableH,wastagePct:stock?((stock-panelArea)/stock)*100:0}}
export type CostInputs={sheetPrice:number;pastingPriceSqft:number;bandingPriceM:number;hardware:number;laborPerSqft:number;wastagePct:number;freightPct:number;overheadsPct:number;profitPct:number;adhesivePerSheet:number;polishSqft:number;polishRate:number}
export function calculateCost(panels:Panel[],opt:{sheets:number},i:CostInputs){const details=panels.map(applyBanding),area=details.reduce((a,d)=>a+d.surfaceSqft,0),band=details.reduce((a,d)=>a+d.bandingMeters,0),material=opt.sheets*i.sheetPrice,pasting=area*i.pastingPriceSqft,edge=band*i.bandingPriceM,consumables=opt.sheets*i.adhesivePerSheet,polish=i.polishSqft*i.polishRate,labor=area*i.laborPerSqft,base=material+pasting+edge+i.hardware+consumables+polish+labor,waste=base*i.wastagePct/100,freight=base*i.freightPct/100,overhead=base*i.overheadsPct/100,subtotal=base+waste+freight+overhead,quote=subtotal*(1+i.profitPct/100);return{areaSqft:n(area),bandingMeters:n(band),material,pasting,edge,hardware:i.hardware,consumables,polish,labor,base,waste,freight,overhead,subtotal,quote}}