'use client'

import { useMemo, useState } from 'react'
import { getSupabaseBrowserClient } from '../../lib/supabase-browser'

const statuses=['NEW','CONTACTED','QUALIFIED','DEMO_SCHEDULED','CONVERTED','CLOSED']
export default function DemoLeadManager({initialLeads}:{initialLeads:any[]}){
 const [leads,setLeads]=useState(initialLeads); const [selected,setSelected]=useState<any>(null); const [status,setStatus]=useState(''); const [notes,setNotes]=useState(''); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('')
 const counts=useMemo(()=>Object.fromEntries(statuses.map(s=>[s,leads.filter(l=>l.status===s).length])),[leads])
 async function save(){if(!selected)return;setBusy(true);setMsg('');const supabase=getSupabaseBrowserClient();const {data,error}=await supabase.rpc('manage_demo_lead',{p_lead_id:selected.id,p_status:status||null,p_assigned_to:null,p_notes:notes||null});if(error){setMsg(error.message);setBusy(false);return}setLeads(prev=>prev.map(l=>l.id===data.id?data:l));setSelected(data);setNotes(data.notes||'');setStatus(data.status);setMsg('Lead updated');setBusy(false)}
 return <><section className="metric-grid">{statuses.map(s=><button className="metric-card" style={{textAlign:'left',cursor:'pointer'}} onClick={()=>setStatus(s)} key={s}><span>{s.replace('_',' ')}</span><strong>{counts[s]}</strong><small>Filter / set status</small></button>)}</section><section className="content-grid"><div className="panel"><div className="panel-head"><div><h2>Incoming requests</h2><p>{leads.length} latest requests</p></div></div><div className="project-list">{leads.map(l=><button key={l.id} onClick={()=>{setSelected(l);setStatus(l.status);setNotes(l.notes||'');setMsg('')}} style={{display:'flex',width:'100%',textAlign:'left',justifyContent:'space-between',gap:20,padding:'16px 0',border:0,borderBottom:'1px solid var(--line,#e5e7eb)',background:'transparent',cursor:'pointer'}}><span><b>{l.name}</b><span style={{display:'block'}}>{l.company||'No company'} · {l.email}</span><small>{l.phone||''}</small></span><em>{l.status}</em></button>)}</div></div>{selected&&<aside className="panel"><div className="panel-head"><div><h2>{selected.name}</h2><p>{selected.company||'No company'} · {selected.email}</p></div><button className="ghost-btn" onClick={()=>setSelected(null)}>Close</button></div><p>{selected.message||'No message provided.'}</p><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Notes<textarea rows={7} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Qualification notes, next action, meeting details..."/></label><button className="primary-btn" onClick={save} disabled={busy}>{busy?'Saving…':'Save lead'}</button>{msg&&<div className="empty" style={{marginTop:12}}>{msg}</div>}</aside>}</section></>
}
