import { createSupabaseServerClient } from '../../lib/supabase-server'

const statuses=['NEW','CONTACTED','QUALIFIED','DEMO_SCHEDULED','CONVERTED','CLOSED']
const nav=[['Dashboard','/executive'],['Customers','/customers'],['Measurements','/measurements'],['Furniture','/furniture'],['Inventory','/inventory'],['Purchasing','/purchasing'],['Manufacturing','/manufacturing'],['Demo Leads','/demo-leads']]

export default async function DemoLeadsPage(){
 const supabase=await createSupabaseServerClient()
 const {data:leads,error}=await supabase.from('millimetre_demo_leads').select('*').order('created_at',{ascending:false}).limit(100)
 return <div className="erp-shell"><aside className="erp-sidebar"><div className="erp-brand"><span className="brand-mark">M</span><div><strong>MILLIMETRE</strong><small>Furniture ERP</small></div></div><div className="workspace">WORKSPACE <span>⌄</span></div><nav>{nav.map(([label,href])=><a key={href} href={href} className={href==='/demo-leads'?'active':''}><span className="nav-dot"/>{label}</a>)}</nav></aside><main className="erp-main"><header className="erp-header"><div><div className="eyebrow">CRM / DEMO LEADS</div><h1>Demo Leads</h1><p>Manage incoming public website demo requests.</p></div><div className="header-actions"><a className="ghost-btn" href="/executive">Dashboard</a></div></header><section className="metric-grid">{statuses.map(s=><div className="metric-card" key={s}><span>{s.replace('_',' ')}</span><strong>{leads?.filter(l=>l.status===s).length??0}</strong><small>Current leads</small></div>)}</section><section className="panel"><div className="panel-head"><div><h2>Incoming requests</h2><p>Newest requests first</p></div></div>{error?<div className="empty">Unable to load demo leads.</div>:!leads?.length?<div className="empty">No demo requests yet.</div>:<div className="project-list">{leads.map(l=><div key={l.id} style={{display:'flex',justifyContent:'space-between',gap:24,alignItems:'center',padding:'16px 0',borderBottom:'1px solid var(--line,#e5e7eb)'}}><div><b>{l.name}</b><span style={{display:'block'}}>{l.company||'No company'} · {l.email}</span><small>{l.phone||''}</small>{l.message&&<p style={{margin:'6px 0 0'}}>{l.message}</p>}</div><div style={{textAlign:'right'}}><strong>{l.status}</strong><small style={{display:'block'}}>{new Date(l.created_at).toLocaleString('en-IN')}</small></div></div>)}</div>}</section></main></div>
}
