import { createSupabaseServerClient } from '../../lib/supabase-server'

export default async function InventoryPage(){
  const supabase=await createSupabaseServerClient()
  const [{data:inventory,error},{data:movements,movementError},{data:reservations,reservationError}]=await Promise.all([
    supabase.from('inventory').select('id,product_id,warehouse_id,quantity,available_quantity,reserved_quantity,quarantine_quantity,reorder_level,products(sku,name,unit),warehouses(code,name)').order('updated_at',{ascending:false}).limit(200),
    supabase.from('millimetre_inventory_movements').select('id,material_id,warehouse_id,movement_type,quantity,reference_no,created_at,goods_receipt_id,goods_receipt_item_id,purchase_order_id').order('created_at',{ascending:false}).limit(100),
    supabase.from('millimetre_inventory_reservations').select('id,material_id,warehouse_id,quantity,status,reference_no,created_at').order('created_at',{ascending:false}).limit(100),
  ])
  const loadError=error||movementError||reservationError
  return <main className="main">
    <header className="top"><div><h1 className="title">Inventory</h1><div className="muted">Stage 14 — stock balance, availability, reservations and movement ledger</div></div><a className="status" href="/manufacturing">Production</a></header>
    <section className="section"><div className="card"><h2>Stock by Product + Warehouse</h2>{loadError?<p role="alert">Unable to load inventory data.</p>:<table className="table"><thead><tr><th>SKU</th><th>Product</th><th>Warehouse</th><th>On hand</th><th>Available</th><th>Reserved</th><th>Quarantine</th><th>Reorder</th></tr></thead><tbody>{(inventory??[]).map((r:any)=><tr key={r.id}><td>{r.products?.sku??'—'}</td><td>{r.products?.name??'—'}</td><td>{r.warehouses?.name??r.warehouses?.code??'—'}</td><td>{r.quantity??0} {r.products?.unit??''}</td><td>{r.available_quantity??0}</td><td>{r.reserved_quantity??0}</td><td>{r.quarantine_quantity??0}</td><td>{r.reorder_level??0}</td></tr>)}{!(inventory??[]).length&&<tr><td colSpan={8}>No inventory records found.</td></tr>}</tbody></table>}</div></section>
    <section className="section"><div className="card"><h2>Inventory Movement Ledger</h2>{!movementError&&<table className="table"><thead><tr><th>Time</th><th>Movement</th><th>Quantity</th><th>Reference</th><th>Material</th><th>Warehouse</th></tr></thead><tbody>{(movements??[]).map((m:any)=><tr key={m.id}><td>{m.created_at?new Date(m.created_at).toLocaleString('en-IN'):'—'}</td><td>{m.movement_type}</td><td>{m.quantity}</td><td>{m.reference_no??m.goods_receipt_id??m.purchase_order_id??'—'}</td><td>{m.material_id}</td><td>{m.warehouse_id}</td></tr>)}{!(movements??[]).length&&<tr><td colSpan={6}>No inventory movements recorded.</td></tr>}</tbody></table>}</div></section>
    <section className="section"><div className="card"><h2>Reservations</h2>{!reservationError&&<table className="table"><thead><tr><th>Created</th><th>Material</th><th>Warehouse</th><th>Quantity</th><th>Status</th><th>Reference</th></tr></thead><tbody>{(reservations??[]).map((r:any)=><tr key={r.id}><td>{r.created_at?new Date(r.created_at).toLocaleString('en-IN'):'—'}</td><td>{r.material_id}</td><td>{r.warehouse_id}</td><td>{r.quantity}</td><td>{r.status}</td><td>{r.reference_no??'—'}</td></tr>)}{!(reservations??[]).length&&<tr><td colSpan={6}>No reservations found.</td></tr>}</tbody></table>}</div></section>
  </main>
}
