import { notFound } from 'next/navigation'
import { createSupabaseServerClient } from '../../../lib/supabase-server'

export default async function ProjectDetailPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params; const s=await createSupabaseServerClient()
 const [{data:project,error},{data:measurements},{data:furniture},{data:tasks}]=await Promise.all([
  s.from('projects').select('id,customer_id,name,code,status,current_stage,site_address,notes,created_at,updated_at').eq('id',id).maybeSingle(),
  s.from('project_measurements').select('id,name,room,width_mm,depth_mm,height_mm,wall_width_mm,wall_height_mm,measured_at').eq('project_id',id).order('created_at',{ascending:false}).limit(20),
  s.from('furniture_items').select('id,name,type,quantity,width_mm,depth_mm,height_mm,measurement_id,updated_at').eq('project_id',id).order('updated_at',{ascending:false}).limit(30),
  s.from('millimetre_tasks').select('id,description,status,priority,due_date,assignee_id,updated_at').eq('project_id',id).order('due_date',{ascending:true}).limit(30)
 ])
 if(error||!project)notFound()
 const links=[['Measurements','/measurements'],['Furniture','/furniture'],['Calculation','/calculation'],['Cutting List','/cutting-list'],['BOM / BOQ','/bom'],['Optimization','/optimization'],['Costing','/costing'],['Quotation','/quotation'],['Approval / Payment','/payments'],['Purchase','/purchasing'],['Goods Receipt + QC','/receiving'],['Inventory','/inventory'],['Production','/manufacturing'],['Production QC','/quality'],['Labels / QR','/labels'],['Delivery','/delivery'],['Installation','/installation'],['Handover','/handover'],['Warranty / Service','/service']]
 return <main className="main"><style>{`.pw-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-end}.pw-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.pw-stat{padding:14px;border:1px solid #e5e8e4;background:#fff}.pw-stat b{display:block;font-size:20px}.pw-stat span,.pw-small{font-size:8px;color:#737a74;text-transform:uppercase;letter-spacing:.08em}.pw-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.pw-table{width:100%;border-collapse:collapse;font-size:10px}.pw-table th,.pw-table td{padding:9px 7px;border-bottom:1px solid #edf0ec;text-align:left}.pw-flow{display:flex;gap:6px;flex-wrap:wrap}.pw-flow a{padding:8px 10px;border:1px solid #e4e7e3;background:#fafbf9;font-size:8px}.pw-note{padding:12px;background:#f6f7f5;border-left:3px solid #d9ddd8;white-space:pre-wrap}.pw-empty{color:#8b928c;font-size:11px}@media(max-width:750px){.pw-head,.pw-grid{display:block}.pw-grid>*{margin-bottom:12px}.pw-stats{grid-template-columns:repeat(2,1fr)}.pw-table{font-size:9px;display:block;overflow-x:auto}}`}</style>
 <header className="top pw-head"><div><div className="muted">PROJECT WORKSPACE / {project.code}</div><h1 className="title">{project.name}</h1><div className="muted">{project.status} · {project.current_stage} · {project.site_address??'Site address not recorded'}</div></div><a className="status" href="/projects">← All Projects</a></header>
 <section className="section"><div className="pw-stats"><div className="pw-stat"><b>{measurements?.length??0}</b><span>Measurements</span></div><div className="pw-stat"><b>{furniture?.length??0}</b><span>Furniture</span></div><div className="pw-stat"><b>{tasks?.length??0}</b><span>Open tasks</span></div><div className="pw-stat"><b>{project.current_stage??'—'}</b><span>Current stage</span></div></div></section>
 <section className="section pw-grid"><div className="card"><h2>Project Brief</h2><p><b>Customer:</b> {project.customer_id??'—'}</p><p><b>Site:</b> {project.site_address??'—'}</p><div className="pw-note">{project.notes??'No project notes recorded. Add the client brief, site constraints, design decisions, MOM and execution instructions here.'}</div></div><div className="card"><h2>Execution Control</h2><p className="pw-small">Stage progression</p><div className="pw-flow">{links.map(([label,href])=><a href={href} key={href}>{label}</a>)}</div></div></section>
 <section className="section pw-grid"><div className="card"><h2>Rooms & Plans</h2>{measurements?.length?<table className="pw-table"><thead><tr><th>Room</th><th>Measurement</th><th>W × D × H</th></tr></thead><tbody>{measurements.map((m:any)=><tr key={m.id}><td>{m.room??'—'}</td><td>{m.name}</td><td>{m.width_mm} × {m.depth_mm??'—'} × {m.height_mm} mm</td></tr>)}</tbody></table>:<p className="pw-empty">No measurements yet. Create the first room/site measurement.</p>}</div><div className="card"><h2>Furniture Allocation</h2>{furniture?.length?<table className="pw-table"><thead><tr><th>Furniture</th><th>Type</th><th>Qty</th><th>Size</th></tr></thead><tbody>{furniture.map((f:any)=><tr key={f.id}><td>{f.name}</td><td>{f.type}</td><td>{f.quantity}</td><td>{f.width_mm} × {f.depth_mm} × {f.height_mm}</td></tr>)}</tbody></table>:<p className="pw-empty">No furniture assigned to this project.</p>}</div></section>
 <section className="section"><div className="card"><h2>Tasks & Milestones</h2>{tasks?.length?<table className="pw-table"><thead><tr><th>Task</th><th>Status</th><th>Priority</th><th>Due</th></tr></thead><tbody>{tasks.map((t:any)=><tr key={t.id}><td>{t.description}</td><td>{t.status}</td><td>{t.priority}</td><td>{t.due_date??'—'}</td></tr>)}</tbody></table>:<p className="pw-empty">No project tasks yet.</p>}</div></section>
 </main>
}