'use client'

import { useEffect, useState } from 'react'
import { getSupabaseBrowserClient } from '../../lib/supabase-browser'

const plans=[{id:'MONTHLY',name:'Monthly',price:2999,period:'/ month'},{id:'YEARLY',name:'Yearly',price:12999,period:'/ year',badge:'Best value'}]

export default function BillingPage(){
 const [sub,setSub]=useState<any>(null),[loading,setLoading]=useState(true),[paying,setPaying]=useState(''),[message,setMessage]=useState(''),[coupon,setCoupon]=useState(''),[applied,setApplied]=useState<any>(null),[checking,setChecking]=useState(''),[cashfreeReady,setCashfreeReady]=useState(false),[verifying,setVerifying]=useState(false)
 useEffect(()=>{const s=getSupabaseBrowserClient();(async()=>{const {data:user}=await s.auth.getUser();if(!user.user){window.location.href='/sign-in';return}const {data,error}=await s.rpc('get_subscription_access');if(error)setMessage(error.message);else setSub(data);setLoading(false)})();
  const script=document.createElement('script');script.src='https://sdk.cashfree.com/js/v3/cashfree.js';script.async=true;script.onload=()=>setCashfreeReady(true);script.onerror=()=>setMessage('Cashfree checkout could not be loaded.');document.head.appendChild(script);return()=>{script.remove()}
 },[])
 useEffect(()=>{const orderId=new URLSearchParams(window.location.search).get('order_id');if(!orderId)return;setVerifying(true);(async()=>{try{const s=getSupabaseBrowserClient();const {data:{session}}=await s.auth.getSession();if(!session)throw new Error('Please sign in again.');const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/cashfree-payment-status`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({order_id:orderId})});const d=await r.json();if(!r.ok)throw new Error(d.error||d.message||'Unable to verify payment.');if(String(d.payment_status||d.status||'').toUpperCase()==='SUCCESS'){const {data:a}=await s.rpc('get_subscription_access');setSub(a);setMessage('Payment confirmed. Your MILLIMETRE account is now active.');setTimeout(()=>window.location.href='/executive',900)}else setMessage('Payment is still pending. Please refresh after Cashfree confirms it.')}catch(e:any){setMessage(e.message||'Payment verification failed.')}finally{setVerifying(false)}})()},[])
 async function applyCoupon(plan:string){if(!coupon.trim()){setApplied(null);return}setMessage('');setChecking(plan);try{const s=getSupabaseBrowserClient();const {data,error}=await s.rpc('calculate_subscription_discount',{p_code:coupon.trim(),p_plan:plan});if(error)throw new Error(error.message);const result=Array.isArray(data)?data[0]:data;if(!result?.valid)throw new Error(result?.message||'Invalid discount code.');setApplied(result)}catch(e:any){setApplied(null);setMessage(e.message||'Unable to validate discount.')}finally{setChecking('')}}
 async function checkout(plan:string){setMessage('');setPaying(plan);try{if(!cashfreeReady)throw new Error('Cashfree checkout is still loading. Please try again in a moment.');const s=getSupabaseBrowserClient();const {data:{session}}=await s.auth.getSession();if(!session)throw new Error('Please sign in again.');const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/cashfree-create-order-v2`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({plan,discount_code:applied?.code&&applied?.original_amount===plans.find(x=>x.id===plan)?.price?applied.code:null})});const data=await r.json();if(!r.ok)throw new Error(data.message||data.error||'Unable to create Cashfree order.');if(!data.payment_session_id)throw new Error('Cashfree did not return a payment session.');const w=window as any;const cashfree=w.Cashfree({mode:(process.env.NEXT_PUBLIC_CASHFREE_MODE||'sandbox') as any});await cashfree.checkout({paymentSessionId:data.payment_session_id,redirectTarget:'_self'});}catch(e:any){setMessage(e.message||'Payment could not be started.');setPaying('')}}
 if(loading)return <main className="auth-page"><div className="auth-card"><h1>Checking access…</h1></div></main>
 return <main className="billing-page"><div className="billing-inner"><a href="/" className="auth-brand"><span>M</span><b>MILLIMETRE</b></a><span className="eyebrow">SUBSCRIPTION</span><h1>{verifying?'Verifying your payment…':'Choose your MILLIMETRE plan.'}</h1><p>{verifying?'We are checking Cashfree payment confirmation.':'Choose a plan to continue using the full MILLIMETRE workspace.'}</p><div className="coupon-box"><label>Discount code</label><div className="coupon-row"><input value={coupon} onChange={e=>{setCoupon(e.target.value);setApplied(null)}} placeholder="Enter code"/><span>Apply on a plan below</span></div><small>Discounts are controlled and validated securely by MILLIMETRE.</small></div><div className="plan-grid">{plans.map(p=>{const isApplied=applied?.code&&applied?.original_amount===p.price;const final=isApplied?Number(applied.final_amount):p.price;const discount=isApplied?Number(applied.discount_amount):0;return <article className="plan-card" key={p.id}>{p.badge&&<small>{p.badge}</small>}<h2>{p.name}</h2>{discount>0?<><del>₹{p.price.toLocaleString('en-IN')}</del><strong>₹{final.toLocaleString('en-IN')}</strong><span>You save ₹{discount.toLocaleString('en-IN')} {applied.discount_type==='PERCENTAGE'?`(${applied.discount_type.toLowerCase()})`:''}</span></>:<><strong>₹{p.price.toLocaleString('en-IN')}</strong><span>{p.period}</span></>}<div className="coupon-action"><button type="button" onClick={()=>applyCoupon(p.id)} disabled={!!checking||verifying}>{checking===p.id?'Checking…':'Apply discount'}</button></div><button className="landing-cta large" disabled={!!paying||verifying} onClick={()=>checkout(p.id)}>{paying===p.id?'Opening Cashfree…':`Choose ${p.name} →`}</button><p>Secure payment through Cashfree. Access activates after verified payment confirmation.</p></article>})}</div>{message&&<div className="auth-error">{message}</div>}<div className="auth-switch">Your account unlocks automatically after Cashfree confirms the payment.</div></div></main>}
