'use client'

import { useEffect, useState } from 'react'
import { getSupabaseBrowserClient } from '../../lib/supabase-browser'
const plans=[{id:'MONTHLY',name:'Monthly',price:'₹2,999',period:'/ month'},{id:'YEARLY',name:'Yearly',price:'₹12,999',period:'/ year',badge:'Best value'}]
export default function BillingPage(){const [sub,setSub]=useState<any>(null);const [loading,setLoading]=useState(true);const [paying,setPaying]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();const {data:user}=await s.auth.getUser();if(!user.user){window.location.href='/sign-in';return}const {data,error}=await s.rpc('get_subscription_access');if(error)setMessage(error.message);else setSub(data);setLoading(false)})()},[])
 async function checkout(plan:string){setMessage('');setPaying(plan);try{const s=getSupabaseBrowserClient();const {data:{session}}=await s.auth.getSession();if(!session)throw new Error('Please sign in again.');const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/cashfree-create-order`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({plan})});const data=await r.json();if(!r.ok)throw new Error(data.message||data.error||'Unable to create Cashfree order.');if(!data.payment_session_id)throw new Error('Cashfree did not return a payment session.');const w=window as any;if(!w.Cashfree){throw new Error('Cashfree checkout is unavailable.');}const cashfree=w.Cashfree({mode:(process.env.NEXT_PUBLIC_CASHFREE_MODE||'sandbox') as any});await cashfree.checkout({paymentSessionId:data.payment_session_id,redirectTarget:'_self'});}catch(e:any){setMessage(e.message||'Payment could not be started.');setPaying('')}}
 if(loading)return <main className="auth-page"><div className="auth-card"><h1>Checking access…</h1></div></main>
 return <main className="billing-page"><script src="https://sdk.cashfree.com/js/v3/cashfree.js" async></script><div className="billing-inner"><a href="/" className="auth-brand"><span>M</span><b>MILLIMETRE</b></a><span className="eyebrow">SUBSCRIPTION</span><h1>Your trial has ended.</h1><p>Choose a plan to continue using the full MILLIMETRE workspace.</p><div className="plan-grid">{plans.map(p=><article className="plan-card" key={p.id}>{p.badge&&<small>{p.badge}</small>}<h2>{p.name}</h2><strong>{p.price}</strong><span>{p.period}</span><button className="landing-cta large" disabled={!!paying} onClick={()=>checkout(p.id)}>{paying===p.id?'Opening Cashfree…':`Choose ${p.name} →`}</button><p>Secure payment through Cashfree. Access activates after verified payment confirmation.</p></article>)}</div>{message&&<div className="auth-error">{message}</div>}<div className="auth-switch">Your account unlocks automatically after Cashfree confirms the payment.</div></div></main>}
