alter table public.projects add column if not exists current_stage text not null default 'FOUNDATION';
alter table public.projects add column if not exists site_address text;

create table if not exists public.packages (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id), furniture_item_id uuid references public.furniture_items(id), package_code text not null unique, package_type text not null default 'PACKAGE', status text not null default 'open', weight_kg numeric, length_mm numeric, width_mm numeric, height_mm numeric, packed_by uuid, packed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.package_items (id uuid primary key default gen_random_uuid(), package_id uuid not null references public.packages(id) on delete cascade, production_piece_id uuid, quantity numeric not null default 1, sequence_no integer, notes text, created_at timestamptz not null default now());
create table if not exists public.vehicles (id uuid primary key default gen_random_uuid(), vehicle_code text not null unique, registration_number text, vehicle_type text, capacity_kg numeric, driver_id uuid, status text not null default 'active', notes text, created_at timestamptz not null default now());
create table if not exists public.delivery_orders (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id), delivery_code text not null unique, status text not null default 'draft', planned_date date, delivery_date date, destination_address text, contact_name text, contact_phone text, vehicle_id uuid references public.vehicles(id), driver_id uuid, dispatched_at timestamptz, delivered_at timestamptz, received_by text, received_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.delivery_items (id uuid primary key default gen_random_uuid(), delivery_order_id uuid not null references public.delivery_orders(id) on delete cascade, package_id uuid references public.packages(id), production_piece_id uuid, furniture_item_id uuid references public.furniture_items(id), quantity numeric not null default 1, status text not null default 'pending', loaded_at timestamptz, delivered_at timestamptz, notes text, created_at timestamptz not null default now());
create table if not exists public.delivery_exceptions (id uuid primary key default gen_random_uuid(), delivery_order_id uuid not null references public.delivery_orders(id) on delete cascade, delivery_item_id uuid references public.delivery_items(id), exception_type text not null, severity text not null default 'major', description text not null, resolved_at timestamptz, resolved_by uuid, notes text, created_at timestamptz not null default now());
create table if not exists public.installation_jobs (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id), delivery_order_id uuid references public.delivery_orders(id), installation_code text not null unique, status text not null default 'planned', planned_date date, started_at timestamptz, completed_at timestamptz, site_address text, supervisor_id uuid, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.installation_items (id uuid primary key default gen_random_uuid(), installation_job_id uuid not null references public.installation_jobs(id) on delete cascade, furniture_item_id uuid references public.furniture_items(id), package_id uuid references public.packages(id), production_piece_id uuid, status text not null default 'pending', installed_at timestamptz, installed_by uuid, notes text, created_at timestamptz not null default now());
create table if not exists public.installation_issues (id uuid primary key default gen_random_uuid(), installation_job_id uuid not null references public.installation_jobs(id) on delete cascade, installation_item_id uuid references public.installation_items(id), issue_type text not null, severity text not null default 'major', description text not null, status text not null default 'open', assigned_to uuid, resolved_at timestamptz, resolution text, created_at timestamptz not null default now());

create table if not exists public.handovers (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id), installation_job_id uuid references public.installation_jobs(id), handover_code text not null unique, status text not null default 'draft', handover_date date, customer_name text, customer_representative text, customer_acceptance_status text not null default 'pending', accepted_at timestamptz, acceptance_method text, acceptance_reference text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.handover_checklist_items (id uuid primary key default gen_random_uuid(), handover_id uuid not null references public.handovers(id) on delete cascade, category text not null, item text not null, expected_result text, actual_result text, result text not null default 'pending', required boolean not null default true, checked_by uuid, checked_at timestamptz, notes text);
create table if not exists public.handover_snags (id uuid primary key default gen_random_uuid(), handover_id uuid not null references public.handovers(id) on delete cascade, project_id uuid not null references public.projects(id), furniture_item_id uuid references public.furniture_items(id), production_piece_id uuid, snag_code text not null unique, category text not null, description text not null, severity text not null default 'minor', status text not null default 'open', assigned_to uuid, due_date date, resolved_at timestamptz, resolution text, created_at timestamptz not null default now());
create table if not exists public.handover_documents (id uuid primary key default gen_random_uuid(), handover_id uuid not null references public.handovers(id) on delete cascade, document_type text not null, document_number text, version integer not null default 1, file_reference text, generated_at timestamptz not null default now(), generated_by uuid, status text not null default 'active');

create table if not exists public.warranties (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id), handover_id uuid not null references public.handovers(id), warranty_code text not null unique, status text not null default 'pending', start_date date, end_date date, duration_value integer, duration_unit text, coverage_type text, terms jsonb not null default '{}'::jsonb, customer_id uuid references public.customers(id), activated_at timestamptz, activated_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.warranty_items (id uuid primary key default gen_random_uuid(), warranty_id uuid not null references public.warranties(id) on delete cascade, furniture_item_id uuid references public.furniture_items(id), production_piece_id uuid, component_id uuid references public.furniture_components(id), coverage_type text, coverage_start date, coverage_end date, terms jsonb not null default '{}'::jsonb, status text not null default 'active', notes text);
create table if not exists public.service_requests (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id), customer_id uuid references public.customers(id), request_code text not null unique, status text not null default 'new', requested_at timestamptz not null default now(), requested_by text, contact_method text, subject text not null, description text not null, priority text not null default 'normal', preferred_visit_date date, location text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.warranty_claims (id uuid primary key default gen_random_uuid(), service_request_id uuid not null references public.service_requests(id), warranty_id uuid references public.warranties(id), claim_code text not null unique, status text not null default 'pending', eligibility text not null default 'requires_review', decision text, reviewed_by uuid, reviewed_at timestamptz, reason text, approved_amount numeric not null default 0, customer_charge numeric not null default 0, notes text, created_at timestamptz not null default now());
create table if not exists public.service_jobs (id uuid primary key default gen_random_uuid(), service_request_id uuid not null references public.service_requests(id), warranty_claim_id uuid references public.warranty_claims(id), project_id uuid references public.projects(id), service_code text not null unique, status text not null default 'open', scheduled_date date, assigned_worker_id uuid, started_at timestamptz, completed_at timestamptz, location text, priority text not null default 'normal', diagnosis text, resolution text, customer_confirmation text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.service_material_requirements (id uuid primary key default gen_random_uuid(), service_job_id uuid not null references public.service_jobs(id) on delete cascade, material_id uuid references public.materials(id), hardware_id uuid, description text not null, required_quantity numeric not null default 0, issued_quantity numeric not null default 0, unit text not null default 'pcs', source text, status text not null default 'required', notes text);
create table if not exists public.service_replacements (id uuid primary key default gen_random_uuid(), service_job_id uuid not null references public.service_jobs(id), original_production_piece_id uuid, replacement_production_piece_id uuid, reason text not null, created_at timestamptz not null default now(), created_by uuid, notes text);
create table if not exists public.service_qc_inspections (id uuid primary key default gen_random_uuid(), service_job_id uuid not null references public.service_jobs(id), production_piece_id uuid, inspection_code text not null unique, status text not null default 'pending', overall_result text, inspected_by uuid, inspected_at timestamptz, notes text);
create table if not exists public.service_events (id uuid primary key default gen_random_uuid(), service_request_id uuid not null references public.service_requests(id) on delete cascade, service_job_id uuid references public.service_jobs(id), event_type text not null, description text, performed_by uuid, event_time timestamptz not null default now(), reference text, notes text);
create table if not exists public.service_costs (id uuid primary key default gen_random_uuid(), service_job_id uuid not null references public.service_jobs(id) on delete cascade, category text not null, source_type text, source_id uuid, quantity numeric not null default 0, unit text, unit_cost numeric not null default 0, total_cost numeric generated always as (round(quantity * unit_cost,2)) stored, notes text, created_at timestamptz not null default now());

create table if not exists public.kpi_definitions (id uuid primary key default gen_random_uuid(), kpi_code text not null unique, name text not null, description text, category text not null, source text not null, calculation_definition text not null, unit text, refresh_policy text, version integer not null default 1, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index if not exists idx_packages_project on public.packages(project_id); create index if not exists idx_delivery_project on public.delivery_orders(project_id); create index if not exists idx_installation_project on public.installation_jobs(project_id); create index if not exists idx_handover_project on public.handovers(project_id); create index if not exists idx_warranty_project on public.warranties(project_id); create index if not exists idx_service_project on public.service_requests(project_id);

do $$ declare t text; begin foreach t in array array['packages','package_items','vehicles','delivery_orders','delivery_items','delivery_exceptions','installation_jobs','installation_items','installation_issues','handovers','handover_checklist_items','handover_snags','handover_documents','warranties','warranty_items','service_requests','warranty_claims','service_jobs','service_material_requirements','service_replacements','service_qc_inspections','service_events','service_costs','kpi_definitions'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists millimetre_authenticated_all_%I on public.%I',t,t); execute format('create policy millimetre_authenticated_all_%I on public.%I for all to authenticated using (true) with check (true)',t,t); end loop; end $$;

create or replace view public.millimetre_project_pipeline as select p.id project_id,p.code project_code,p.name project_name,p.status,p.current_stage,c.name customer_name,count(distinct f.id) furniture_count,count(distinct d.id) delivery_count,count(distinct i.id) installation_count,count(distinct h.id) handover_count,count(distinct s.id) service_request_count from public.projects p left join public.customers c on c.id=p.customer_id left join public.furniture_items f on f.project_id=p.id left join public.delivery_orders d on d.project_id=p.id left join public.installation_jobs i on i.project_id=p.id left join public.handovers h on h.project_id=p.id left join public.service_requests s on s.project_id=p.id group by p.id,p.code,p.name,p.status,p.current_stage,c.name;

insert into public.kpi_definitions(kpi_code,name,description,category,source,calculation_definition,unit,refresh_policy) values
('ACTIVE_PROJECTS','Active Projects','Projects not closed or cancelled','PROJECTS','projects','count projects where status not in (closed,cancelled)','count','near-real-time'),
('AVAILABLE_STOCK','Available Stock','Physical stock less reservations and non-usable stock','INVENTORY','inventory ledger','physical - reserved - non_usable','quantity','near-real-time'),
('PRODUCTION_PROGRESS','Production Progress','Completed acceptable pieces divided by required pieces','PRODUCTION','production pieces','completed / required * 100','percent','near-real-time'),
('OPEN_SERVICE_CASES','Open Service Cases','Service requests not closed or cancelled','SERVICE','service_requests','count where status not in (closed,cancelled)','count','near-real-time'),
('HANDOVER_READY','Handover Ready','Handovers ready for customer acceptance','HANDOVER','handovers','count status = ready_for_acceptance','count','near-real-time')
on conflict (kpi_code) do nothing;
