'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'

type Material={id:string;code:string;name:string;category:string;thickness_mm:number;sheet_length_mm:number|null;sheet_width_mm:number|null;unit_cost:number;edge_cost_per_m:number;active:boolean}
type Pasting={id:string;code:string;name:string;pasting_type:string;thickness_mm:number;grain_direction:string;sheet_length_mm:number|null;sheet_width_mm:number|null;unit:string;unit_cost:number;edge_band_code:string|null;active:boolean}
type Hardware={id:string;code:string;name:string;category:string;brand:string|null;specification:string|null;unit:string;unit_cost:number;active:boolean}
const blankM={code:'',name:'',category:'CARCASS',thickness_mm:'18',sheet_length_mm:'2438.4',sheet_width_mm:'1219.2',unit_cost:'0',edge_cost_per_m:'0'}
const blankP={code:'',name:'',pasting_type:'LAMINATE',thickness_mm:'0.8',grain_direction:'NONE',sheet_length_mm:'2440',sheet_width_mm:'1220',unit:'sheet',unit_cost:'0',edge_band_code:''}
const blankH={code:'',name:'',category:'HINGE',brand:'',specification:'',unit:'pcs',unit_cost:'0'}
export default function MasterData(){
 const [tab,setTab]=useState('materials'),[materials,setMaterials]=useState<Material[]>([]),[pastings,setPastings]=useState<Pasting[]>([]),[hardware,setHardware]=useState<Hardware[]>([]),[mf,setMf]=useState(blankM),[pf,setPf]=useState(blankP),[hf,setHf]=useState(blankH),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 async function load(){const [m,p,h]=await Promise.all([supabase.from('materials').select('*').order('name'),supabase.from('millimetre_pastings').select('*').order('name'),supabase.from('millimetre_hardware').select('*').order('name')]);setMaterials((m.data??[]) as Material[]);setPastings((p.data??[]) as Pasting[]);setHardware((h.data??[]) as Hardware[])}
 useEffect(()=>{load()},[])
 async function addMaterial(){setBusy(true);setMsg('');const r=await supabase.from('materials').insert({code:mf.code.trim().toUpperCase(),name:mf.name.trim(),category:mf.category,thickness_mm:Number(mf.thickness_mm),sheet_length_mm:Number(mf.sheet_length_mm)||null,sheet_width_mm:Number(mf.sheet_width_mm)||null,unit_cost:Number(mf.unit_cost)||0,edge_cost_per_m:Number(mf.edge_cost_per_m)||0});if(r.error)setMsg(r.error.message);else{setMf(blankM);await load();setMsg('Carcass material added.')}setBusy(false)}
 async function addPasting(){setBusy(true);setMsg('');const r=await supabase.from('millimetre_pastings').insert({code:pf.code.trim().toUpperCase(),name:pf.name.trim(),pasting_type:pf.pasting_type,thickness_mm:Number(pf.thickness_mm),grain_direction:pf.grain_direction,sheet_length_mm:Number(pf.sheet_length_mm)||null,sheet_width_mm:Number(pf.sheet_width_mm)||null,unit:pf.unit,unit_cost:Number(pf.unit_cost)||0,edge_band_code:pf.edge_band_code||null});if(r.error)setMsg(r.error.message);else{setPf(blankP);await load();setMsg('Pasting added.')}setBusy(false)}
 async function addHardware(){setBusy(true);setMsg('');const r=await supabase.from('millimetre_hardware').insert({code:hf.code.trim().toUpperCase(),name:hf.name.trim(),category:hf.category,brand:hf.brand||null,specification:hf.specification||null,unit:hf.unit,unit_cost:Number(hf.unit_cost)||0});if(r.error)setMsg(r.error.message);else{setHf(blankH);await load();setMsg('Hardware item added.')}setBusy(false)}
 async function toggle(table:string,id:string,active:boolean){const r=await supabase.from(table).update({active:!active}).eq('id',id);if(r.error)setMsg(r.error.message);else load()}
 const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
 return <main className="main"><header className="top"><div><h1 className="title">Foundation Master Data</h1><div className="muted">Carcass materials, pastings, hardware and procurement rates</div></div><a className="status" href="/suppliers">Supplier Master</a></header><div className="tabs"><button className={tab==='materials'?'active':''} onClick={()=>setTab('materials')}>Carcass Materials ({materials.length})</button><button className={tab==='pastings'?'active':''} onClick={()=>setTab('pastings')}>Pastings / Laminates ({pastings.length})</button><button className={tab==='hardware'?'active':''} onClick={()=>setTab('hardware')}>Hardware ({hardware.length})</button></div>{msg&&<div className="notice">{msg}</div>}
 {tab==='materials'&&<section className="section"><div className="card"><h2>Add carcass material</h2><div className="form-grid">{[['code','Material code'],['name','Name'],['category','Category'],['thickness_mm','Thickness mm'],['sheet_length_mm','Sheet length mm'],['sheet_width_mm','Sheet width mm'],['unit_cost','Sheet cost'],['edge_cost_per_m','Edge cost / m']].map(([k,l])=><label key={k}>{l}<input value={(mf as any)[k]} onChange={e=>setMf(f=>({...f,[k]:e.target.value}))}/></label>)}</div><button className="primary" disabled={busy} onClick={addMaterial}>Add material</button></div><div className="card"><table className="table"><thead><tr><th>Code</th><th>Material</th><th>Category</th><th>Thickness</th><th>Sheet</th><th>Cost</th><th>Status</th></tr></thead><tbody>{materials.map(m=><tr key={m.id}><td>{m.code}</td><td>{m.name}</td><td>{m.category}</td><td>{m.thickness_mm} mm</td><td>{m.sheet_length_mm||'—'} × {m.sheet_width_mm||'—'}</td><td>{money(m.unit_cost)}</td><td><button onClick={()=>toggle('materials',m.id,m.active)}>{m.active?'Active':'Inactive'}</button></td></tr>)}{!materials.length&&<tr><td colSpan={7}>No carcass materials yet.</td></tr>}</tbody></table></div></section>}
 {tab==='pastings'&&<section className="section"><div className="card"><h2>Add pasting / laminate</h2><div className="form-grid">{[['code','Code'],['name','Name'],['thickness_mm','Thickness mm'],['sheet_length_mm','Sheet length mm'],['sheet_width_mm','Sheet width mm'],['unit_cost','Sheet cost'],['edge_band_code','Edge-band code']].map(([k,l])=><label key={k}>{l}<input value={(pf as any)[k]} onChange={e=>setPf(f=>({...f,[k]:e.target.value}))}/></label>)}<label>Type<select value={pf.pasting_type} onChange={e=>setPf(f=>({...f,pasting_type:e.target.value}))}><option>LAMINATE</option><option>VENEER</option><option>PRELAMINATED</option><option>OTHER</option></select></label><label>Grain direction<select value={pf.grain_direction} onChange={e=>setPf(f=>({...f,grain_direction:e.target.value}))}><option>NONE</option><option>LENGTH</option><option>WIDTH</option><option>BOTH</option></select></label></div><button className="primary" disabled={busy} onClick={addPasting}>Add pasting</button></div><div className="card"><table className="table"><thead><tr><th>Code</th><th>Name</th><th>Type</th><th>Thickness</th><th>Sheet</th><th>Cost</th><th>Status</th></tr></thead><tbody>{pastings.map(p=><tr key={p.id}><td>{p.code}</td><td>{p.name}</td><td>{p.pasting_type}</td><td>{p.thickness_mm} mm</td><td>{p.sheet_length_mm||'—'} × {p.sheet_width_mm||'—'}</td><td>{money(p.unit_cost)}</td><td><button onClick={()=>toggle('millimetre_pastings',p.id,p.active)}>{p.active?'Active':'Inactive'}</button></td></tr>)}{!pastings.length&&<tr><td colSpan={7}>No pastings yet.</td></tr>}</tbody></table></div></section>}
 {tab==='hardware'&&<section className="section"><div className="card"><h2>Add hardware</h2><div className="form-grid">{[['code','Hardware code'],['name','Name'],['category','Category'],['brand','Brand'],['specification','Specification'],['unit','Unit'],['unit_cost','Unit cost']].map(([k,l])=><label key={k}>{l}<input value={(hf as any)[k]} onChange={e=>setHf(f=>({...f,[k]:e.target.value}))}/></label>)}</div><button className="primary" disabled={busy} onClick={addHardware}>Add hardware</button></div><div className="card"><table className="table"><thead><tr><th>Code</th><th>Hardware</th><th>Category</th><th>Brand</th><th>Unit</th><th>Cost</th><th>Status</th></tr></thead><tbody>{hardware.map(h=><tr key={h.id}><td>{h.code}</td><td>{h.name}<div className="muted">{h.specification||''}</div></td><td>{h.category}</td><td>{h.brand||'—'}</td><td>{h.unit}</td><td>{money(h.unit_cost)}</td><td><button onClick={()=>toggle('millimetre_hardware',h.id,h.active)}>{h.active?'Active':'Inactive'}</button></td></tr>)}{!hardware.length&&<tr><td colSpan={7}>No hardware yet.</td></tr>}</tbody></table></div></section>}
 <style jsx>{`.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.tabs button{padding:10px 14px;border:1px solid #ddd;border-radius:10px;background:white}.tabs .active{font-weight:700}.form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:14px 0}.form-grid label{display:flex;flex-direction:column;gap:6px;font-size:13px}.form-grid input,.form-grid select{padding:10px;border:1px solid #ddd;border-radius:8px}@media(max-width:800px){.form-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.form-grid{grid-template-columns:1fr}.table{min-width:760px}.card{overflow-x:auto}}`}</style></main>
}