const templates = [
  ['Kitchen','Base units, wall units, tall units, fillers, shutters and configurable internal modules.'],
  ['Wardrobe','Sliding or hinged wardrobes with shelves, drawers, partitions and repeatable door systems.'],
  ['Bedroom','Beds, side tables, storage, study units and coordinated bedroom packages.'],
  ['Living','TV units, storage walls, display units and custom living-room furniture.'],
  ['Office','Workstations, storage, meeting furniture and modular commercial interiors.'],
  ['Custom','Start from a clean structure when the project requires a completely new furniture family.'],
]

export default function TemplatesPage(){return <main className="public-page"><nav className="public-nav"><a className="landing-logo" href="/"><span className="landing-mark">M</span><span><b>MILLIMETRE</b><small>Furniture manufacturing OS</small></span></a><div className="public-links"><a href="/platform">Platform</a><a href="/features">Features</a><a href="/templates">Templates</a><a href="/pricing">Pricing</a></div><div className="landing-actions"><a className="landing-login" href="/executive">Open workspace</a><a className="landing-cta" href="/#demo">Request demo</a></div></nav><section className="public-hero"><span>FURNITURE TEMPLATES</span><h1>Start with a proven structure. Configure it for the project.</h1><p>Reusable furniture templates give your team a consistent starting point while keeping dimensions, materials and outputs adaptable.</p></section><section className="template-showcase">{templates.map(([t,d],i)=><article key={t}><div className="template-number">{String(i+1).padStart(2,'0')}</div><div className="template-visual"><div className="cabinet"><i></i><i></i><i></i></div></div><h2>{t}</h2><p>{d}</p><a href="/executive">Use in workspace →</a></article>)}</section><section className="template-bottom"><div><span>PARAMETRIC OUTPUT</span><h2>One template can feed the next stages.</h2><p>Configure the furniture, then carry its structured information into calculation, cutting, BOM, costing and production.</p></div><div className="output-chain"><b>Furniture</b><span>→</span><b>Components</b><span>→</span><b>Cut list</b><span>→</span><b>BOM</b><span>→</span><b>Cost</b></div></section><footer className="landing-footer"><div className="landing-logo"><span className="landing-mark">M</span><span><b>MILLIMETRE</b><small>Furniture manufacturing OS</small></span></div><span>Design → Cost → Buy → Make → Deliver → Install</span><span>© 2026 MILLIMETRE</span></footer></main>}
